### **Python `numpy` Module: Overview, Concepts, and Theory**

The `numpy` module is one of the most widely used libraries in Python for numerical and scientific computing. It provides efficient operations on large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. `numpy` is a foundational library in Python, especially in fields such as data science, machine learning, scientific computing, and engineering, due to its ability to perform fast, vectorized operations.

---

### **Key Concepts of the `numpy` Module:**

1. **N-dimensional Array (ndarray):**

   - The core object in `numpy` is the `ndarray`, a multi-dimensional array object that represents arrays of data. The `ndarray` allows for efficient element-wise operations, broadcasting, and more.
   - A key feature of `ndarray` is its ability to hold homogeneous data types, making it much more efficient than Python lists for numerical operations.

2. **Array Operations:**

   - `numpy` supports fast operations on arrays, such as element-wise arithmetic operations, logical operations, and more. This allows you to perform calculations on large datasets without having to write loops.

3. **Vectorization:**

   - Vectorization refers to the practice of replacing explicit loops with optimized, vectorized operations. This makes the code more concise, faster, and easier to read. `numpy` enables this through its built-in functions and broadcasting capabilities.

4. **Broadcasting:**

   - Broadcasting is a technique used by `numpy` to perform operations on arrays of different shapes in a way that allows the smaller array to be broadcast across the larger array.

5. **Mathematical Functions:**

   - `numpy` provides a vast array of mathematical functions to perform operations like trigonometric calculations, linear algebra, statistics, and more.

6. **Random Number Generation:**

   - `numpy` has powerful tools for generating random numbers and random sampling from various probability distributions. This is crucial for tasks like simulations, statistical analysis, and machine learning.

7. **Linear Algebra:**

   - `numpy` provides a set of tools for working with linear algebra problems, such as matrix multiplication, eigenvalues, and solving systems of linear equations.

8. **Integration with Other Libraries:**
   - `numpy` is integrated with other scientific libraries like `scipy`, `matplotlib`, and `pandas`, allowing for seamless workflows for scientific and data analysis.

---

### **Main Data Structures in `numpy`:**

#### 1. **ndarray (N-dimensional array):**

- The `ndarray` is the central data structure in `numpy`. It is a grid of values, all of the same type, indexed by a tuple of non-negative integers. `ndarray` supports multi-dimensional data and has many useful methods for mathematical operations.

- **Creating an ndarray:**

  ```python
  import numpy as np
  # Creating a 1D array (vector)
  arr = np.array([1, 2, 3, 4])
  print(arr)  # Output: [1 2 3 4]

  # Creating a 2D array (matrix)
  arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
  print(arr_2d)
  # Output:
  # [[1 2]
  #  [3 4]
  #  [5 6]]
  ```

- **Shape of an ndarray:**

  ```python
  print(arr_2d.shape)  # Output: (3, 2) -> 3 rows, 2 columns
  ```

- **Dimensions of an ndarray:**

  ```python
  print(arr_2d.ndim)  # Output: 2 -> 2D array
  ```

- **Data type of an ndarray:**
  ```python
  print(arr_2d.dtype)  # Output: int64 (or float64, depending on the data type)
  ```

#### 2. **Array Indexing and Slicing:**

- **Indexing:**
  You can access individual elements of an `ndarray` using indices.

  ```python
  print(arr_2d[1, 0])  # Access the element at row 1, column 0 -> Output: 3
  ```

- **Slicing:**
  You can slice arrays to access specific portions of the data.
  ```python
  print(arr_2d[:2, 1:])  # Output: [[2]
                          #          [4]]
  ```

---

### **Array Operations in `numpy`:**

1. **Element-wise Arithmetic Operations:**

   - You can perform arithmetic operations on entire arrays without the need for explicit loops.

   ```python
   arr1 = np.array([1, 2, 3])
   arr2 = np.array([4, 5, 6])
   print(arr1 + arr2)  # Output: [5 7 9]
   print(arr1 * arr2)  # Output: [ 4 10 18]
   ```

2. **Mathematical Operations on Arrays:**

   - `numpy` supports a wide range of mathematical operations, including trigonometric, logarithmic, and exponential functions.

   ```python
   arr = np.array([0, np.pi/2, np.pi])
   print(np.sin(arr))  # Output: [0. 1. 0.]
   ```

3. **Linear Algebra Operations:**

   - `numpy` has functions for matrix multiplication, eigenvalue computation, and solving linear equations.

   ```python
   A = np.array([[1, 2], [3, 4]])
   B = np.array([[5, 6], [7, 8]])
   print(np.dot(A, B))  # Matrix multiplication
   ```

4. **Array Broadcasting:**

   - Broadcasting allows for element-wise operations between arrays of different shapes by "stretching" the smaller array across the larger one.

   ```python
   arr = np.array([1, 2, 3])
   print(arr + 5)  # Output: [6 7 8] - Broadcasting addition of scalar to array
   ```

5. **Statistical Operations:**
   - `numpy` provides a range of functions for computing statistical measures such as mean, median, standard deviation, and more.
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(np.mean(arr))  # Output: 3.0
   print(np.std(arr))   # Output: 1.4142135623730951
   ```

---

### **Advanced Features of `numpy`:**

1. **Random Number Generation:**

   - `numpy` includes a module (`numpy.random`) for generating random numbers from various distributions.

   ```python
   rand_arr = np.random.rand(3, 3)  # Generate a 3x3 array of random floats between 0 and 1
   print(rand_arr)

   # Generate random integers between 0 and 10
   int_arr = np.random.randint(0, 10, size=(2, 3))
   print(int_arr)
   ```

2. **Reshaping and Resizing Arrays:**

   - `numpy` allows for reshaping arrays into different dimensions.

   ```python
   arr = np.array([1, 2, 3, 4, 5, 6])
   reshaped_arr = arr.reshape(2, 3)  # Convert the 1D array into a 2D array (2x3)
   print(reshaped_arr)
   ```

3. **Stacking and Splitting Arrays:**

   - You can stack arrays along different axes (horizontally, vertically, etc.), and split large arrays into smaller ones.

   ```python
   arr1 = np.array([1, 2, 3])
   arr2 = np.array([4, 5, 6])
   stacked_arr = np.vstack((arr1, arr2))  # Vertical stack
   print(stacked_arr)
   ```

4. **Indexing with Boolean Arrays:**
   - `numpy` allows you to use boolean conditions to index and filter arrays.
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr[arr > 3])  # Output: [4 5]
   ```

---

### **Commonly Used `numpy` Functions:**

| Function              | Description                                          |
| --------------------- | ---------------------------------------------------- |
| `np.array()`          | Create an ndarray from a list or tuple.              |
| `np.zeros()`          | Create an ndarray filled with zeros.                 |
| `np.ones()`           | Create an ndarray filled with ones.                  |
| `np.linspace()`       | Create an ndarray of evenly spaced values.           |
| `np.arange()`         | Generate a range of values in an ndarray.            |
| `np.reshape()`        | Reshape an ndarray without changing its data.        |
| `np.mean()`           | Compute the mean of an array.                        |
| `np.sum()`            | Compute the sum of an array.                         |
| `np.dot()`            | Compute the dot product of two arrays.               |
| `np.transpose()`      | Transpose the array (swap rows and columns).         |
| `np.linalg.inv()`     | Compute the inverse of a matrix.                     |
| `np.random.rand()`    | Generate random numbers from a uniform distribution. |
| `np.random.randint()` | Generate random integers.                            |

---

### **Use Cases of `numpy`:**

1. **Scientific Computing:**

   - Used extensively in scientific fields for numerical simulations, solving differential equations, and handling large datasets.

2. **Data Science and Machine Learning:**

   - `numpy` is often the first step in data preprocessing and manipulation before feeding data into machine learning models.

3. **Image Processing:**

   - In image processing, `numpy` arrays are used to represent images as arrays of pixel values for manipulation and transformation.

4. **Econometrics and Finance:**
   - `numpy` is frequently used to perform statistical analysis, model financial instruments, and process large financial datasets.

---

### **Conclusion:**

The `numpy` library is a powerful tool for numerical and scientific computing in Python. Its efficient handling of multi-dimensional arrays, vectorized operations, and integration with other scientific libraries make it essential for anyone working with data analysis, machine learning, or scientific computing. By using `numpy`, you can perform complex mathematical operations efficiently and easily.


Creating arrays in NumPy is fundamental to working with numerical data in Python, as NumPy arrays offer efficient ways to store and manipulate large datasets. Below, I'll break down the key concepts, theory, and methods involved in creating and working with NumPy arrays.

### **What is NumPy?**

NumPy (Numerical Python) is a powerful library used for numerical computing. It provides support for arrays, matrices, and many mathematical functions. The central object in NumPy is the **array**, which is a grid of values (all of the same type) indexed by a tuple of non-negative integers.

### **Key Concepts in NumPy Arrays**

1. **Array Object**:
   - The main object in NumPy is `ndarray`, which is a multi-dimensional array object. It is an efficient and flexible data structure.
2. **Homogeneous Data Type**:

   - Unlike Python lists, NumPy arrays contain elements of the same data type, such as integers, floats, or complex numbers.

3. **Dimensions**:

   - **1D Array**: A simple array like a list (e.g., `[1, 2, 3, 4]`).
   - **2D Array**: A matrix (e.g., `[[1, 2], [3, 4], [5, 6]]`).
   - **3D Array**: A three-dimensional array (e.g., a stack of matrices).

4. **Shape and Size**:

   - The **shape** of an array represents the number of elements along each axis (dimension). For example, a 2D array of size 3x4 would have a shape `(3, 4)`.
   - The **size** of the array represents the total number of elements in the array (e.g., size of shape `(3, 4)` would be 12).

5. **Indexing**:
   - NumPy arrays can be indexed in a similar way to Python lists, but with the added benefit of supporting multiple dimensions.
   - You can index using integers, slices, or boolean indexing.

### **Creating NumPy Arrays**

NumPy provides several functions to create arrays, each serving different needs. Below are the most common ways to create NumPy arrays.

#### **1. From a Python List**

You can convert a Python list (or any other iterable) into a NumPy array using `np.array()`.

```python
import numpy as np

# 1D array from a list
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

# 2D array from a list of lists
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)
```

#### **2. Creating Arrays with Default Values**

- **Zeros Array**:
  Creates an array filled with zeros.

  ```python
  arr_zeros = np.zeros((2, 3))  # 2x3 array of zeros
  print(arr_zeros)
  ```

- **Ones Array**:
  Creates an array filled with ones.

  ```python
  arr_ones = np.ones((2, 3))  # 2x3 array of ones
  print(arr_ones)
  ```

- **Empty Array**:
  Creates an array without initializing values (i.e., the values are uninitialized).

  ```python
  arr_empty = np.empty((2, 3))  # 2x3 uninitialized array
  print(arr_empty)
  ```

- **Identity Matrix**:
  Creates an identity matrix (a square matrix with ones on the diagonal and zeros elsewhere).

  ```python
  arr_eye = np.eye(3)  # 3x3 identity matrix
  print(arr_eye)
  ```

#### **3. Creating Arrays with a Range of Values**

- **`np.arange()`**:
  Creates an array with values in a specified range (similar to Python's `range()` function).

  ```python
  arr_range = np.arange(0, 10, 2)  # Array with values from 0 to 10 with a step of 2
  print(arr_range)
  ```

- **`np.linspace()`**:
  Creates an array with a specified number of evenly spaced values over a specified range.

  ```python
  arr_linspace = np.linspace(0, 10, 5)  # 5 equally spaced values from 0 to 10
  print(arr_linspace)
  ```

#### **4. Random Arrays**

NumPy provides functionality to generate arrays with random values:

- **Random Float Numbers**:
  Generates an array with random float values between 0 and 1.

  ```python
  arr_random = np.random.rand(2, 3)  # 2x3 array with random float values
  print(arr_random)
  ```

- **Random Integers**:
  Generates an array with random integer values within a specified range.

  ```python
  arr_randint = np.random.randint(1, 10, (2, 3))  # Random integers between 1 and 10
  print(arr_randint)
  ```

#### **5. Creating Arrays with Specific Data Types**

You can specify the data type of the array using the `dtype` argument.

```python
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(arr_float)
```

### **Array Attributes**

1. **`shape`**: Returns the dimensions of the array.

   ```python
   print(arr_2d.shape)  # Output: (2, 3)
   ```

2. **`ndim`**: Returns the number of dimensions (axes) of the array.

   ```python
   print(arr_2d.ndim)  # Output: 2
   ```

3. **`size`**: Returns the total number of elements in the array.

   ```python
   print(arr_2d.size)  # Output: 6
   ```

4. **`dtype`**: Returns the data type of the array.

   ```python
   print(arr_2d.dtype)  # Output: dtype('int64')
   ```

5. **`itemsize`**: Returns the size (in bytes) of each element of the array.

   ```python
   print(arr_2d.itemsize)  # Output: 8 (for int64)
   ```

### **Array Indexing and Slicing**

1. **Indexing**:

   - Access individual elements using indices.

   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr[0])  # Output: 1
   ```

2. **Slicing**:

   - Extract subarrays using slicing notation.

   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr[1:4])  # Output: [2, 3, 4]
   ```

3. **Multi-dimensional Indexing**:

   - For 2D and higher-dimensional arrays, you can index using multiple indices.

   ```python
   arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
   print(arr_2d[1, 2])  # Output: 6
   ```

4. **Boolean Indexing**:

   - You can index an array using a condition, which returns the elements that satisfy the condition.

   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr[arr > 3])  # Output: [4, 5]
   ```

### **Array Operations**

NumPy supports a variety of mathematical operations on arrays. Some examples include:

1. **Element-wise Operations**:

   - You can perform element-wise operations on arrays, such as addition, subtraction, multiplication, etc.

   ```python
   arr1 = np.array([1, 2, 3])
   arr2 = np.array([4, 5, 6])
   print(arr1 + arr2)  # Output: [5, 7, 9]
   ```

2. **Matrix Operations**:

   - For matrix multiplication, use `np.dot()` or `@` operator.

   ```python
   arr1 = np.array([[1, 2], [3, 4]])
   arr2 = np.array([[5, 6], [7, 8]])
   print(np.dot(arr1, arr2))  # Output: [[19, 22], [43, 50]]
   ```

3. **Universal Functions (ufuncs)**:

   - NumPy provides **ufuncs**, which are functions that operate element-wise on arrays. Examples include `np.sqrt()`, `np.sin()`, `np.exp()`, etc.

   ```python
   arr = np.array([1, 4, 9])
   print(np.sqrt(arr))  # Output: [1. 2. 3.]
   ```

### **Conclusion**

Creating and manipulating arrays in NumPy is a crucial skill in data analysis, scientific computing, and machine learning. By understanding the various ways to create arrays and how to work with them (e.g., through indexing, slicing, and operations), you'll be able to efficiently handle data in numerical formats.


NumPy (Numerical Python) is one of the most important libraries for scientific computing in Python. It provides support for arrays (multi-dimensional arrays), matrices, and a wide range of mathematical operations. Below, we’ll go through all the core concepts and theory behind NumPy arrays.

### **1. What is a NumPy Array?**

A **NumPy array** is a grid of values of the same data type, indexed by a tuple of non-negative integers. It can be of any number of dimensions (1D, 2D, 3D, etc.), and is more efficient than Python's built-in lists.

#### **Key Features of NumPy Arrays:**

- **Homogeneous**: All elements in a NumPy array must have the same type.
- **Multidimensional**: NumPy arrays can be of any dimension, such as 1D, 2D, 3D, etc.
- **Efficient**: Operations on NumPy arrays are faster compared to Python lists due to internal optimizations and low-level implementations.
- **Vectorized operations**: NumPy arrays allow you to perform element-wise operations without needing explicit loops.

### **2. Creating NumPy Arrays**

NumPy provides various ways to create arrays:

- **From a List**: You can create a NumPy array by passing a Python list to `np.array()`.

  ```python
  import numpy as np
  arr = np.array([1, 2, 3])
  ```

- **Using `np.zeros()`**: Creates an array of zeros.

  ```python
  arr = np.zeros((3, 4))  # 3x4 matrix filled with 0s
  ```

- **Using `np.ones()`**: Creates an array of ones.

  ```python
  arr = np.ones((2, 3))  # 2x3 matrix filled with 1s
  ```

- **Using `np.arange()`**: Creates an array with values spaced evenly in a given range.

  ```python
  arr = np.arange(0, 10, 2)  # Array with values from 0 to 10 (exclusive) with a step of 2
  ```

- **Using `np.linspace()`**: Creates an array of evenly spaced numbers over a specified range.

  ```python
  arr = np.linspace(0, 1, 5)  # 5 numbers from 0 to 1
  ```

- **Random arrays**: NumPy has several functions for generating random numbers, like `np.random.rand()`, `np.random.randn()`, etc.

### **3. Basic Array Operations**

You can perform a variety of operations on NumPy arrays:

- **Element-wise arithmetic operations**: These operations apply element-wise (on the corresponding elements of the arrays).

  ```python
  arr1 = np.array([1, 2, 3])
  arr2 = np.array([4, 5, 6])
  sum_arr = arr1 + arr2  # Element-wise addition
  ```

- **Broadcasting**: NumPy allows for operations between arrays of different shapes. This is called broadcasting, and it automatically adjusts the shapes to make the operation compatible.

  ```python
  arr1 = np.array([1, 2, 3])
  arr2 = np.array([1])
  sum_arr = arr1 + arr2  # Broadcasting arr2 to arr1's shape
  ```

- **Dot product (matrix multiplication)**:
  ```python
  arr1 = np.array([[1, 2], [3, 4]])
  arr2 = np.array([[5, 6], [7, 8]])
  result = np.dot(arr1, arr2)  # Matrix multiplication
  ```

### **4. Array Properties**

You can access various properties of a NumPy array:

- **Shape**: Returns the dimensions of the array.

  ```python
  arr = np.array([[1, 2], [3, 4], [5, 6]])
  print(arr.shape)  # Output: (3, 2)
  ```

- **Size**: Returns the total number of elements in the array.

  ```python
  print(arr.size)  # Output: 6
  ```

- **ndim**: Returns the number of dimensions (axes).

  ```python
  print(arr.ndim)  # Output: 2
  ```

- **dtype**: Returns the data type of the elements.

  ```python
  print(arr.dtype)  # Output: int64 (or int32 depending on the system)
  ```

- **Itemsize**: Returns the size (in bytes) of one element in the array.

  ```python
  print(arr.itemsize)  # Output: 8 (for int64)
  ```

- **Data**: Gives the buffer containing the array data.
  ```python
  print(arr.data)
  ```

### **5. Indexing and Slicing**

Just like Python lists, NumPy arrays support indexing and slicing:

- **1D Arrays**:

  ```python
  arr = np.array([10, 20, 30, 40])
  print(arr[2])  # Access the 3rd element: Output is 30
  ```

- **2D Arrays**:

  ```python
  arr = np.array([[1, 2], [3, 4], [5, 6]])
  print(arr[1, 0])  # Access the element in the 2nd row, 1st column: Output is 3
  ```

- **Slicing**:

  ```python
  arr = np.array([1, 2, 3, 4, 5])
  print(arr[1:4])  # Output: [2 3 4] (slices from index 1 to 3)
  ```

- **2D Slicing**:
  ```python
  arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  print(arr[:2, 1:3])  # Output: [[2 3], [5 6]]
  ```

### **6. Array Manipulation**

You can reshape, concatenate, split, and manipulate arrays in various ways:

- **Reshaping arrays**:

  ```python
  arr = np.array([1, 2, 3, 4, 5, 6])
  reshaped = arr.reshape((2, 3))  # Reshape into a 2x3 matrix
  ```

- **Concatenation**:

  ```python
  arr1 = np.array([1, 2, 3])
  arr2 = np.array([4, 5, 6])
  concatenated = np.concatenate((arr1, arr2))  # Concatenate arrays
  ```

- **Splitting**:

  ```python
  arr = np.array([1, 2, 3, 4, 5, 6])
  split_arr = np.split(arr, 3)  # Split into 3 parts
  ```

- **Flattening**:
  ```python
  arr = np.array([[1, 2], [3, 4]])
  flattened = arr.flatten()  # Convert the 2D array into a 1D array
  ```

### **7. Advanced Concepts**

- **Broadcasting**: This allows NumPy to perform arithmetic operations on arrays of different shapes. It “broadcasts” the smaller array to the size of the larger one.

- **Linear Algebra**: NumPy provides a suite of functions for linear algebra, such as `np.linalg.inv()` (matrix inversion), `np.linalg.eig()` (eigenvalues), and more.

- **Random Numbers**: The `np.random` module generates random numbers and distributions:

  ```python
  rand_array = np.random.rand(3, 3)  # Random array of shape (3, 3)
  ```

- **Statistical Operations**: NumPy provides functions for statistical analysis, like `np.mean()`, `np.median()`, `np.std()`, `np.var()`, etc.

  ```python
  arr = np.array([1, 2, 3, 4, 5])
  print(np.mean(arr))  # Output: 3.0 (Mean of the array)
  ```

- **Element-wise functions**: NumPy supports a wide range of mathematical functions that work element-wise on arrays:
  ```python
  arr = np.array([1, 4, 9])
  sqrt_arr = np.sqrt(arr)  # Element-wise square root
  ```

### **8. Efficiency Considerations**

NumPy arrays are much more efficient than Python lists, especially for large datasets. They are implemented in C, allowing them to be much faster for array operations. Moreover, they use less memory and can be used in parallel processing, which further optimizes performance.

### **9. Conclusion**

NumPy arrays are a fundamental part of scientific computing in Python. They provide:

- Fast operations on large datasets.
- Support for multi-dimensional data structures.
- A wide array of mathematical and statistical functions.
- Efficient memory management.
- Flexibility through broadcasting and reshaping.

Mastering NumPy arrays is essential for data analysis, machine learning, and any other scientific computing tasks in Python.


Understanding arrays in general and their properties and concepts can help you grasp how data is stored, accessed, and manipulated efficiently. Arrays are a foundational data structure in many programming languages, and they are essential for handling large datasets in scientific computing, machine learning, and data analysis.

Let’s explore **arrays** in detail, focusing on their properties, concepts, and the theory behind them.

### **1. What is an Array?**

An **array** is a collection of elements (values or variables), each identified by an index or a key. All elements in an array are of the **same type**, and they are stored contiguously in memory. Arrays allow for efficient indexing, random access, and manipulation of data.

#### **Key Characteristics of Arrays:**

- **Homogeneous**: All elements must be of the same data type (integers, floats, strings, etc.).
- **Fixed Size**: The size of an array is fixed upon creation (although dynamic arrays, like Python lists, can grow or shrink).
- **Index-based Access**: Elements are accessed using their index, with the first element having an index of 0 (in most programming languages).
- **Contiguous Memory Allocation**: Arrays are stored in contiguous memory locations for efficient access.

### **2. Types of Arrays**

Arrays can be categorized based on their dimensions and data types:

#### **1D Arrays (One-dimensional arrays)**

These arrays are like lists in which data is stored linearly.

Example:

```python
arr = [1, 2, 3, 4, 5]  # A 1D array of integers
```

#### **2D Arrays (Two-dimensional arrays)**

These arrays have rows and columns, like a matrix.

Example:

```python
arr = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]  # A 2D array (3x3 matrix)
```

#### **3D and Higher-dimensional Arrays**

Higher-dimensional arrays represent more complex structures, like tensors (commonly used in deep learning).

Example:

```python
arr = [
  [
    [1, 2],
    [3, 4]
  ],
  [
    [5, 6],
    [7, 8]
  ]
]  # A 3D array (2x2x2)
```

### **3. Basic Operations on Arrays**

Arrays support a wide range of operations, such as:

- **Indexing**: Accessing individual elements of the array.

  ```python
  arr = [1, 2, 3, 4, 5]
  print(arr[2])  # Output: 3
  ```

- **Slicing**: Extracting a part (subarray) from the array.

  ```python
  arr = [1, 2, 3, 4, 5]
  print(arr[1:4])  # Output: [2, 3, 4]
  ```

- **Modification**: Updating elements in the array.

  ```python
  arr[2] = 10  # Change the 3rd element
  print(arr)  # Output: [1, 2, 10, 4, 5]
  ```

- **Concatenation**: Joining multiple arrays together.

  ```python
  arr1 = [1, 2]
  arr2 = [3, 4]
  print(arr1 + arr2)  # Output: [1, 2, 3, 4]
  ```

- **Multiplication**: Repeating the array elements.

  ```python
  arr = [1, 2, 3]
  print(arr * 2)  # Output: [1, 2, 3, 1, 2, 3]
  ```

- **Reshaping**: Changing the shape of the array (in case of multidimensional arrays).
  ```python
  import numpy as np
  arr = np.array([1, 2, 3, 4, 5, 6])
  reshaped = arr.reshape(2, 3)  # 2x3 matrix
  ```

### **4. Array Properties**

Arrays have various properties that provide useful information about their structure:

#### **Length**

The length of an array is the number of elements in it.

- **1D Array**: The length is the number of elements in the array.
  ```python
  arr = [1, 2, 3]
  len(arr)  # Output: 3
  ```

#### **Shape**

In multi-dimensional arrays, the shape represents the dimensions of the array, i.e., how many rows and columns (or higher dimensions) it has.

- **2D Array Shape**: It’s represented as a tuple `(rows, columns)`.

  ```python
  arr = [[1, 2], [3, 4]]
  shape = (2, 2)  # 2 rows and 2 columns
  ```

- **3D Array Shape**: It’s represented as a tuple `(depth, rows, columns)`.
  ```python
  arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
  shape = (2, 2, 2)  # 2 layers, 2 rows, 2 columns
  ```

#### **Size**

The size of an array refers to the total number of elements in the array, calculated by multiplying all the dimensions in the shape.

- For a 2D array of shape `(3, 4)`, the size is `3 * 4 = 12`.

#### **Data Type (dtype)**

The `dtype` of an array specifies the type of elements it holds (e.g., integer, float, etc.).

```python
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)
```

#### **Item Size**

The `itemsize` property tells you how many bytes are used to store each element of the array.

```python
arr = np.array([1, 2, 3])
print(arr.itemsize)  # Output: 8 (for int64)
```

#### **Number of Dimensions (ndim)**

The `ndim` property tells you how many dimensions the array has.

```python
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)  # Output: 2 (2D array)
```

### **5. Array Representation in Memory**

Arrays, especially in low-level programming languages, are stored in contiguous memory locations, which allows for efficient access and manipulation. The memory layout for arrays is a **contiguous block of memory**, which contrasts with lists, which are more fragmented.

- **Static Arrays**: In languages like C, arrays have a fixed size, and their memory is allocated statically.
- **Dynamic Arrays**: In languages like Python, arrays (such as lists) can resize dynamically.

### **6. Advantages of Using Arrays**

- **Efficient Memory Usage**: Arrays store elements in contiguous blocks of memory, making them more efficient than linked lists.
- **Faster Access**: Arrays allow constant-time access (O(1)) to elements using indices, while lists require traversing to reach an element.
- **Cache Friendliness**: Because elements are stored contiguously, they are more cache-friendly, leading to faster processing.

### **7. Array Algorithms**

Some common algorithms that apply to arrays:

- **Searching**: Finding an element in the array.

  - **Linear Search**: O(n) time complexity.
  - **Binary Search** (only applicable to sorted arrays): O(log n) time complexity.

- **Sorting**: Arranging elements in a specified order.

  - **Bubble Sort**, **Merge Sort**, **Quick Sort**, etc.
  - **Time complexity** varies, but for efficient sorting, **Quick Sort** (O(n log n)) is commonly used.

- **Merging Arrays**: Combining two or more sorted arrays into a single sorted array.
  - **Merge Algorithm**: Used in **Merge Sort** to combine two sorted arrays.

### **8. Multidimensional Arrays**

Multidimensional arrays represent data in higher dimensions (2D, 3D, and beyond). These are essential for tasks like image processing, machine learning (tensor operations), and scientific computing.

- **Matrix Operations**: Operations like matrix multiplication, transposition, and inverse require 2D arrays.

  ```python
  arr1 = np.array([[1, 2], [3, 4]])
  arr2 = np.array([[5, 6], [7, 8]])
  result = np.dot(arr1, arr2)  # Matrix multiplication
  ```

- **Tensors**: In machine learning, multi-dimensional arrays (tensors) are used for storing data (e.g., 3D arrays for images, 4D arrays for batches of images).

### **9. Array Libraries**

In Python, **NumPy** is the most popular library for working with arrays. It provides:

- Efficient array operations and mathematical functions.
- Advanced features like broadcasting, multidimensional array support, and linear algebra.
- Support for **N-dimensional arrays** (ndarray), a general-purpose array object.

### **Conclusion**

Arrays are a fundamental data structure in computer science and are widely used in programming for efficiently storing and accessing data. The key properties of arrays—such as fixed size, homogeneous elements, and direct indexing—enable fast and efficient data handling. Understanding arrays’ properties, operations, and algorithms is crucial for working with large datasets and performing tasks like numerical computation, data analysis, and machine learning.

In Python, **NumPy arrays** take this concept further by adding advanced capabilities like multidimensional arrays, broadcasting, and vectorized operations, which make them a powerful tool for scientific computing.


Initializing **NumPy arrays** correctly is essential for efficient data storage, computation, and manipulation. **NumPy** provides several ways to initialize arrays, each with specific use cases depending on the kind of data you're working with.

Let’s dive deep into **NumPy array initialization**, covering all concepts and methods with examples, along with the theory behind them.

### **1. Basics of NumPy Array Initialization**

NumPy arrays are initialized using the **`numpy.array()`** function, but NumPy also offers a variety of other functions to create arrays with specific properties or patterns.

The general syntax for creating a NumPy array is:

```python
import numpy as np

arr = np.array(data, dtype=None, copy=True, order='K', subok=False, ndmin=0)
```

Where:

- `data`: Input data (like a list, tuple, or another array).
- `dtype`: Desired data type for the array.
- `copy`: Whether the new array is a copy of the data (`True` by default).
- `order`: Memory layout order (`'C'` for row-major, `'F'` for column-major).
- `subok`: If `True`, sub-classes of `ndarray` will be passed down.
- `ndmin`: Minimum number of dimensions for the result.

### **2. Initializing Arrays from Lists or Tuples**

The most common way to create a NumPy array is by converting a Python list (or a tuple) to a NumPy array using **`np.array()`**.

- **Example**:

  ```python
  import numpy as np
  # 1D array
  arr1 = np.array([1, 2, 3, 4, 5])
  print(arr1)

  # 2D array (matrix)
  arr2 = np.array([[1, 2], [3, 4], [5, 6]])
  print(arr2)
  ```

- **Creating a 3D Array**:

  ```python
  arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
  print(arr3)
  ```

- **Custom Data Types**: You can specify the type of the array’s elements.
  ```python
  arr = np.array([1, 2, 3], dtype=np.float64)
  print(arr)  # Output: [1. 2. 3.]
  ```

### **3. Creating Arrays with Specific Values**

NumPy provides several built-in functions to create arrays filled with specific values, which is useful when you need to initialize an array with particular properties.

#### **1. Zeros**

- **`np.zeros()`** creates an array filled with zeros.
- You can specify the shape and the **dtype** if needed.

- **Example**:

  ```python
  arr = np.zeros((3, 4))  # 3x4 array of zeros
  print(arr)

  arr2 = np.zeros((2, 2), dtype=int)  # 2x2 array of zeros with integer data type
  print(arr2)
  ```

#### **2. Ones**

- **`np.ones()`** creates an array filled with ones.
- You can specify the shape and **dtype**.

- **Example**:

  ```python
  arr = np.ones((3, 3))  # 3x3 array of ones
  print(arr)

  arr2 = np.ones((2, 2), dtype=float)  # 2x2 array of ones with float data type
  print(arr2)
  ```

#### **3. Full**

- **`np.full()`** creates an array filled with a specified value.
- It allows you to specify both the shape and the fill value.

- **Example**:
  ```python
  arr = np.full((2, 3), 7)  # 2x3 array filled with 7
  print(arr)
  ```

#### **4. Identity Matrix (Eye)**

- **`np.eye()`** creates an identity matrix (a square matrix with ones on the diagonal and zeros elsewhere).

- **Example**:
  ```python
  arr = np.eye(3)  # 3x3 identity matrix
  print(arr)
  ```

### **4. Arrays with Random Values**

NumPy offers functions for generating arrays of random numbers, which is useful for simulations, machine learning, and data sampling.

#### **1. Random Uniform Distribution**

- **`np.random.rand()`** generates an array of random numbers from a uniform distribution between 0 and 1.

- **Example**:
  ```python
  arr = np.random.rand(2, 3)  # 2x3 array of random values between 0 and 1
  print(arr)
  ```

#### **2. Random Normal Distribution**

- **`np.random.randn()`** generates an array of random numbers from a standard normal distribution (mean 0, variance 1).

- **Example**:
  ```python
  arr = np.random.randn(2, 2)  # 2x2 array of random values from standard normal distribution
  print(arr)
  ```

#### **3. Random Integers**

- **`np.random.randint()`** generates random integers from a specified range.

- **Example**:
  ```python
  arr = np.random.randint(0, 10, size=(2, 3))  # 2x3 array of random integers between 0 and 10
  print(arr)
  ```

#### **4. Random Choice**

- **`np.random.choice()`** generates a random sample from a given 1D array (with or without replacement).

- **Example**:
  ```python
  arr = np.random.choice([1, 2, 3, 4, 5], size=(2, 2), replace=True)  # 2x2 array from the list with replacement
  print(arr)
  ```

### **5. Arrays with Sequences**

NumPy provides convenient functions for creating arrays with regular sequences of values.

#### **1. arange**

- **`np.arange()`** generates arrays with values from a start to an end, with a specified step size.

- **Example**:

  ```python
  arr = np.arange(0, 10, 2)  # Creates an array from 0 to 10 with step size 2
  print(arr)

  arr2 = np.arange(0, 5, 0.5)  # Creates an array from 0 to 5 with step size 0.5
  print(arr2)
  ```

#### **2. linspace**

- **`np.linspace()`** generates an array of evenly spaced numbers over a specified interval. The number of values to generate is given as the third argument.

- **Example**:
  ```python
  arr = np.linspace(0, 10, 5)  # Creates an array with 5 values from 0 to 10
  print(arr)
  ```

#### **3. logspace**

- **`np.logspace()`** generates numbers that are spaced evenly on a log scale. It’s often used for logarithmic scales in graphing.

- **Example**:
  ```python
  arr = np.logspace(0, 2, 5)  # Creates an array of 5 values from 10^0 to 10^2 (log scale)
  print(arr)
  ```

### **6. Initialization Using `np.empty()` and `np.empty_like()`**

These functions create arrays without initializing them, i.e., they contain random uninitialized values. This can be useful when you need an empty array that you plan to fill later.

- **`np.empty()`** creates an uninitialized array of the specified shape and dtype.

  - **Example**:
    ```python
    arr = np.empty((2, 3))  # Creates an empty 2x3 array
    print(arr)
    ```

- **`np.empty_like()`** creates an uninitialized array with the same shape and dtype as an existing array.

  - **Example**:
    ```python
    arr = np.array([[1, 2], [3, 4]])
    empty_arr = np.empty_like(arr)
    print(empty_arr)
    ```

### **7. Creating Arrays Using `np.fromfunction()`**

- **`np.fromfunction()`** creates an array by applying a function to the coordinates of the array. This is useful for creating arrays with patterns based on their indices.

- **Example**:

  ```python
  arr = np.fromfunction(lambda i, j: i + j, (3, 3))
  print(arr)
  ```

  In this example, the value at each position in the array is the sum of its row index and column index.

### **8. Creating Arrays Using `np.fromiter()`**

- **`np.fromiter()`** creates a NumPy array from an iterator (e.g., a list, generator, or any iterable).

- **Example**:
  ```python
  arr = np.fromiter(range(5), dtype=int)
  print(arr)
  ```

### **9. Advanced Initialization Techniques**

#### **1. Creating Arrays with `np.tile()`**

- **`np.tile()`** creates an array by repeating an array multiple times.

- **Example**:
  ```python
  arr = np.array([1, 2])
  tiled_arr = np.tile(arr, (3, 2))  # Repeat arr 3 times along rows and 2 times along columns
  print(tiled_arr)
  ```

#### **2. Creating Arrays with `np.reshape()`**

- **`np.reshape()`** can be used to change the shape of an array without changing its data.

- **Example**:
  ```python
  arr = np.array([1, 2, 3, 4, 5, 6])
  reshaped_arr = arr.reshape((2, 3))
  print(reshaped_arr)
  ```

### **Conclusion**

NumPy provides a rich set of functions for creating and initializing arrays, making it an extremely powerful tool for numerical computing. Whether you're initializing arrays with zeros, ones, random values, or specific patterns, NumPy gives you flexibility and speed. Understanding these initialization techniques is essential for efficiently handling data, especially when working with large datasets, performing simulations, or working in data science and machine learning.

By mastering the different ways to initialize arrays in **NumPy**, you'll be able to select the best method for your specific use case, enhancing the efficiency and performance of your computations.


In **NumPy**, **indexing** and **slicing** are fundamental operations that allow you to access and manipulate subsets of data within arrays. These concepts are essential for efficiently working with NumPy arrays, especially when dealing with large datasets or multidimensional arrays.

Let’s explore all the **indexing** and **slicing** concepts in **NumPy** in detail:

---

### **1. Basic Indexing in NumPy**

Indexing is the process of accessing individual elements or subsets of elements in an array.

#### **1.1. 1D Array Indexing**

For a one-dimensional array (1D array), indexing works similarly to standard Python lists.

- **Example**:

  ```python
  import numpy as np
  arr = np.array([10, 20, 30, 40, 50])
  print(arr[0])  # Output: 10 (Access the first element)
  print(arr[3])  # Output: 40 (Access the fourth element)
  ```

- **Negative Indexing**: You can use negative indices to access elements from the end of the array.
  ```python
  print(arr[-1])  # Output: 50 (Last element)
  print(arr[-2])  # Output: 40 (Second last element)
  ```

#### **1.2. 2D Array Indexing**

For a two-dimensional array (2D array), you need to specify the row and column indices to access an element.

- **Example**:
  ```python
  arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  print(arr_2d[1, 2])  # Output: 6 (Element at row 1, column 2)
  ```

#### **1.3. 3D Array Indexing**

In a three-dimensional array (3D array), you access elements by specifying the index for the depth, row, and column.

- **Example**:
  ```python
  arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
  print(arr_3d[1, 0, 1])  # Output: 6 (Element at depth 1, row 0, column 1)
  ```

---

### **2. Slicing in NumPy**

Slicing refers to accessing a subarray by specifying a range of indices.

#### **2.1. 1D Array Slicing**

You can slice a 1D array by specifying a start, stop, and step (i.e., `arr[start:stop:step]`).

- **Example**:

  ```python
  arr = np.array([10, 20, 30, 40, 50])
  print(arr[1:4])  # Output: [20 30 40] (Elements from index 1 to 3)
  print(arr[:3])   # Output: [10 20 30] (First 3 elements)
  print(arr[::2])  # Output: [10 30 50] (Every second element)
  ```

  - **Start**: The index to start the slice (inclusive).
  - **Stop**: The index to stop the slice (exclusive).
  - **Step**: The step size between indices.

#### **2.2. 2D Array Slicing**

For a 2D array, you can slice along both axes (rows and columns). The syntax is `arr[start_row:end_row, start_col:end_col]`.

- **Example**:
  ```python
  arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  print(arr_2d[1:3, 0:2])  # Output: [[4 5] [7 8]] (Rows 1 and 2, Columns 0 and 1)
  print(arr_2d[:2, 1:])     # Output: [[2 3] [5 6]] (First 2 rows, columns 1 to the end)
  ```

#### **2.3. 3D Array Slicing**

In a 3D array, slicing works similarly to 2D arrays but with an extra dimension (depth).

- **Example**:
  ```python
  arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
  print(arr_3d[0:2, 0:1, :])  # Output: [[[1 2]] [[5 6]]] (Depth 0 and 1, Row 0, all columns)
  ```

---

### **3. Advanced Indexing and Slicing**

#### **3.1. Integer Indexing**

In NumPy, you can index arrays with other arrays (usually integers). This is useful when you want to select specific elements by index.

- **Example**:

  ```python
  arr = np.array([10, 20, 30, 40, 50])
  print(arr[[1, 3]])  # Output: [20 40] (Select elements at indices 1 and 3)
  ```

  **Note**: You can also use an array of indices for multidimensional arrays.

#### **3.2. Boolean Indexing**

Boolean indexing allows you to index an array with a boolean mask (True or False values). This is powerful when you want to select elements that meet specific conditions.

- **Example**:

  ```python
  arr = np.array([10, 20, 30, 40, 50])
  mask = arr > 30  # Create a boolean mask where elements > 30 are True
  print(arr[mask])  # Output: [40 50] (Select elements greater than 30)

  # Alternatively, directly with a condition:
  print(arr[arr > 30])  # Output: [40 50]
  ```

#### **3.3. Fancy Indexing**

Fancy indexing allows you to access multiple elements or modify them at once using a list or array of indices. It works with both 1D and multidimensional arrays.

- **Example**:

  ```python
  arr = np.array([10, 20, 30, 40, 50])
  indices = [0, 2, 4]
  print(arr[indices])  # Output: [10 30 50] (Elements at indices 0, 2, and 4)
  ```

  For multidimensional arrays, fancy indexing works along both axes:

  ```python
  arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
  print(arr_2d[[0, 2], [1, 0]])  # Output: [2 5] (Select elements at (0,1) and (2,0))
  ```

#### **3.4. Modifying Arrays with Indexing**

You can also use indexing to modify values in an array.

- **Example**:

  ```python
  arr = np.array([10, 20, 30, 40, 50])
  arr[1:4] = [200, 300, 400]  # Modify elements from index 1 to 3
  print(arr)  # Output: [ 10 200 300 400  50]

  # Using Boolean indexing to modify values
  arr[arr > 200] = 999  # Modify elements greater than 200
  print(arr)  # Output: [ 10 200 999 999  50]
  ```

---

### **4. Other Advanced Indexing Techniques**

#### **4.1. Ellipsis (…) for Multi-Dimensional Arrays**

The ellipsis (`...`) can be used to represent multiple colons (`:`) in a slice for arrays with more than two dimensions. This is useful for handling high-dimensional arrays without explicitly specifying all indices.

- **Example**:
  ```python
  arr_4d = np.array([[[[1], [2]], [[3], [4]]], [[[5], [6]], [[7], [8]]]])
  print(arr_4d[..., 0])  # Output: [[[1 3] [5 7]]]
  ```

#### **4.2. Using `np.newaxis` to Increase Dimensions**

You can use `np.newaxis` to increase the number of dimensions of an array, which is particularly useful for broadcasting operations.

- **Example**:

  ```python
  arr = np.array([1, 2, 3])
  arr2d = arr[:, np.newaxis]  # Convert 1D array to 2D (3x1)
  print(arr2d)
  ```

  The output will be:

  ```
  [[1]
   [2]
   [3]]
  ```

#### **4.3. Indexing with `np.r_[]` and `np.c_[]`**

- **`np.r_[]`** and **`np.c_[]`** are used for creating slices and stacking arrays along rows (for `r_[]`) or columns (for `c_[]`).

- **Example**:

  ```python
  arr1 = np.array([1, 2, 3])
  arr2 = np.array([4, 5, 6])
  result = np.r_[arr1, arr2]  # Stack along rows (vertical)
  print(result)  # Output: [1 2 3 4 5 6]

  result = np.c_[arr1, arr2]  # Stack along columns (horizontal)
  print(result)
  ```

  Output:

  ```
  [[1 4]
   [2 5]
   [3 6]]
  ```

---

### **5. Practical Examples of Indexing and Slicing**

#### **Example 1: Selecting Rows and Columns**

Suppose you have a 2D array representing a matrix:

```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

- To select all rows and the first column:

  ```python
  print(arr_2d[:, 0])  # Output: [1 4 7]
  ```

- To select the second row:

  ```python
  print(arr_2d[1, :])  # Output: [4 5 6]
  ```

- To select a submatrix (first two rows and first two columns):
  ```python
  print(arr_2d[:2, :2])  # Output: [[1 2] [4 5]]
  ```

#### **Example 2: Using Boolean Indexing**

You can create conditions based on the array's values and select elements based on those conditions.

```python
arr = np.array([10, 20, 30, 40, 50])
condition = arr > 30
print(arr[condition])  # Output: [40 50]
```

---

### **Conclusion**

**Indexing** and **slicing** are essential for accessing and manipulating data within NumPy arrays. Understanding these concepts enables you to work efficiently with **1D**, **2D**, and **3D arrays**, and even higher-dimensional arrays. From basic indexing to advanced slicing, Boolean indexing, and fancy indexing, NumPy provides powerful tools to interact with data in

arrays flexibly and intuitively.


NumPy arrays (officially called `ndarray` objects) are the cornerstone of numerical computing in Python. They are highly efficient for storing and manipulating large datasets. Understanding their properties is crucial for effective data handling and manipulation.

Here's an exhaustive overview of the key properties of NumPy arrays:

---

## I. Shape and Dimensions

These properties describe the structure and size of the array.

1.  **`ndim`**:

    - **Description**: The number of dimensions (axes) of the array. Also known as the rank of the array.
    - **Type**: Integer.
    - **Example**:

      ```python
      import numpy as np
      arr_0d = np.array(5)           # A scalar (0-dimensional)
      arr_1d = np.array([1, 2, 3])   # A vector (1-dimensional)
      arr_2d = np.array([[1, 2], [3, 4]]) # A matrix (2-dimensional)

      print(f"arr_0d.ndim: {arr_0d.ndim}") # Output: 0
      print(f"arr_1d.ndim: {arr_1d.ndim}") # Output: 1
      print(f"arr_2d.ndim: {arr_2d.ndim}") # Output: 2
      ```

2.  **`shape`**:

    - **Description**: A tuple of integers indicating the size of the array in each dimension.
    - **Type**: Tuple of integers.
    - **Example**:

      ```python
      import numpy as np
      arr_1d = np.array([1, 2, 3])
      arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2 rows, 3 columns
      arr_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) # 2 "layers", 2 rows, 2 columns

      print(f"arr_1d.shape: {arr_1d.shape}") # Output: (3,)
      print(f"arr_2d.shape: {arr_2d.shape}") # Output: (2, 3)
      print(f"arr_3d.shape: {arr_3d.shape}") # Output: (2, 2, 2)
      ```

    - **Mutable**: You can change the shape of an array using `arr.shape = new_shape` or `arr.reshape()`, as long as the total number of elements remains the same.

3.  **`size`**:

    - **Description**: The total number of elements in the array. This is equal to the product of the elements of `shape`.
    - **Type**: Integer.
    - **Example**:
      ```python
      import numpy as np
      arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
      print(f"arr_2d.size: {arr_2d.size}") # Output: 6 (2 * 3)
      ```

---

## II. Data Type Information

These properties describe the type of data stored within the array.

1.  **`dtype`**:

    - **Description**: An object describing the data type of the elements in the array. This is fundamental for how NumPy stores and operates on data.
    - **Type**: `numpy.dtype` object.
    - **Example**:

      ```python
      import numpy as np
      arr_int = np.array([1, 2, 3])
      arr_float = np.array([1.0, 2.0])
      arr_bool = np.array([True, False])
      arr_str = np.array(['a', 'b'])

      print(f"arr_int.dtype: {arr_int.dtype}")       # Output: int64 (or int32 depending on system)
      print(f"arr_float.dtype: {arr_float.dtype}")   # Output: float64
      print(f"arr_bool.dtype: {arr_bool.dtype}")     # Output: bool
      print(f"arr_str.dtype: {arr_str.dtype}")       # Output: <U1 (Unicode string of length 1)
      ```

    - **Common dtypes**: `int8`, `int16`, `int32`, `int64`, `uint8`, `float16`, `float32`, `float64`, `complex64`, `complex128`, `bool`, `object`.

2.  **`itemsize`**:

    - **Description**: The size in bytes of each element of the array.
    - **Type**: Integer.
    - **Example**:

      ```python
      import numpy as np
      arr_int64 = np.array([1, 2, 3], dtype=np.int64)
      arr_float32 = np.array([1.0, 2.0], dtype=np.float32)

      print(f"arr_int64.itemsize: {arr_int64.itemsize} bytes")   # Output: 8 bytes (for int64)
      print(f"arr_float32.itemsize: {arr_float32.itemsize} bytes") # Output: 4 bytes (for float32)
      ```

3.  **`nbytes`**:

    - **Description**: The total bytes consumed by the array data. This is equal to `arr.size * arr.itemsize`.
    - **Type**: Integer.
    - **Example**:
      ```python
      import numpy as np
      arr = np.zeros((100, 100), dtype=np.float64) # 100x100 array of float64
      print(f"arr.nbytes: {arr.nbytes} bytes") # Output: 80000 bytes (100*100*8)
      ```

---

## III. Memory Layout and Internal Representation

These properties provide insights into how the array's data is stored in memory.

1.  **`strides`**:

    - **Description**: A tuple of integers indicating the number of bytes to skip in each dimension to go to the next element. It tells you how many bytes you need to move to get from one element to the next along a particular axis.
    - **Type**: Tuple of integers.
    - **Example**:

      ```python
      import numpy as np
      arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64) # Each int64 is 8 bytes
      print(f"arr.strides: {arr.strides}")
      # Output: (24, 8)
      # Explanation:
      # - To move from one row to the next (downwards, 1st dimension), you skip 3 elements * 8 bytes/element = 24 bytes.
      # - To move from one column to the next (rightwards, 2nd dimension), you skip 1 element * 8 bytes/element = 8 bytes.

      arr_c_order = np.array([[1, 2], [3, 4]], order='C') # Default C-order (row-major)
      arr_f_order = np.array([[1, 2], [3, 4]], order='F') # Fortran-order (column-major)

      print(f"arr_c_order.strides: {arr_c_order.strides}") # Output: (16, 8) for int64
      print(f"arr_f_order.strides: {arr_f_order.strides}") # Output: (8, 16) for int64
      ```

2.  **`flags`**:

    - **Description**: A dictionary-like object containing information about the memory layout of the array. Important flags include:
      - `C_CONTIGUOUS` / `C_ARRAY`: `True` if the data is C-contiguous (row-major).
      - `F_CONTIGUOUS` / `F_ARRAY`: `True` if the data is Fortran-contiguous (column-major).
      - `OWNDATA`: `True` if the array owns its own data (i.e., it's not a view of another array).
      - `WRITEABLE`: `True` if the data can be modified.
    - **Type**: `numpy.flagsobj` object.
    - **Example**:

      ```python
      import numpy as np
      arr = np.arange(6).reshape(2, 3)
      print("arr.flags:")
      print(arr.flags)
      # Output will show something like:
      #   C_CONTIGUOUS : True
      #   F_CONTIGUOUS : False
      #   OWNDATA : True
      #   WRITEABLE : True
      #   ALIGNED : True
      #   WRITEBACKIFCOPY : False

      view_arr = arr.view() # Create a view, not a copy
      print("\nview_arr.flags (OWNDATA is False):")
      print(view_arr.flags)
      # Output will show OWNDATA : False
      ```

---

## IV. Other Useful Properties

1.  **`real`**:

    - **Description**: The real part of the array elements. For non-complex dtypes, this is the array itself.
    - **Type**: `ndarray` (a view of the original or a copy).
    - **Example**:
      ```python
      import numpy as np
      arr_complex = np.array([1+2j, 3-4j])
      print(f"arr_complex.real: {arr_complex.real}") # Output: [1. 3.]
      arr_real = np.array([1, 2])
      print(f"arr_real.real: {arr_real.real}")       # Output: [1 2]
      ```

2.  **`imag`**:

    - **Description**: The imaginary part of the array elements. For non-complex dtypes, this will be an array of zeros.
    - **Type**: `ndarray` (a view of the original or a copy).
    - **Example**:
      ```python
      import numpy as np
      arr_complex = np.array([1+2j, 3-4j])
      print(f"arr_complex.imag: {arr_complex.imag}") # Output: [ 2. -4.]
      arr_real = np.array([1, 2])
      print(f"arr_real.imag: {arr_real.imag}")       # Output: [0. 0.]
      ```

3.  **`T`**:

    - **Description**: The transposed view of the array. For a 2D array, rows become columns and columns become rows. For higher dimensions, axes are permuted.
    - **Type**: `ndarray` (a view of the original).
    - **Example**:
      ```python
      import numpy as np
      arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
      print("Original 2D array:\n", arr_2d)
      print("Transposed 2D array (arr_2d.T):\n", arr_2d.T)
      # Output:
      # Original 2D array:
      #  [[1 2 3]
      #   [4 5 6]]
      # Transposed 2D array (arr_2d.T):
      #  [[1 4]
      #   [2 5]
      #   [3 6]]
      ```

4.  **`flat`**:

    - **Description**: An object that allows iteration over all elements of the array as if it were a 1D array, regardless of its original shape.
    - **Type**: `numpy.flatiter` object.
    - **Example**:
      ```python
      import numpy as np
      arr_2d = np.array([[1, 2], [3, 4]])
      print("Iterating using arr_2d.flat:")
      for x in arr_2d.flat:
          print(x, end=" ") # Output: 1 2 3 4
      ```

5.  **`base`**:

    - **Description**: The object whose memory is used by this array. If the array owns its own memory, its `base` attribute is `None`. This is useful for checking if an array is a view of another array.
    - **Type**: `ndarray` or `None`.
    - **Example**:

      ```python
      import numpy as np
      original_arr = np.array([1, 2, 3, 4, 5])
      view_arr = original_arr[1:4] # view_arr is a view of original_arr

      print(f"original_arr.base is None: {original_arr.base is None}") # Output: True
      print(f"view_arr.base is original_arr: {view_arr.base is original_arr}") # Output: True
      ```

Understanding these properties provides a deep insight into how NumPy arrays work and helps in writing more efficient and correct code for numerical operations.


NumPy arrays (officially called `ndarray` objects) are the cornerstone of numerical computing in Python. They are highly efficient for storing and manipulating large datasets. Understanding their properties is crucial for effective data handling and manipulation.

Here's an exhaustive overview of the key properties of NumPy arrays:

---

## I. Shape and Dimensions

These properties describe the structure and size of the array.

1.  **`ndim`**:

    - **Description**: The number of dimensions (axes) of the array. Also known as the rank of the array.
    - **Type**: Integer.
    - **Example**:

      ```python
      import numpy as np
      arr_0d = np.array(5)           # A scalar (0-dimensional)
      arr_1d = np.array([1, 2, 3])   # A vector (1-dimensional)
      arr_2d = np.array([[1, 2], [3, 4]]) # A matrix (2-dimensional)

      print(f"arr_0d.ndim: {arr_0d.ndim}") # Output: 0
      print(f"arr_1d.ndim: {arr_1d.ndim}") # Output: 1
      print(f"arr_2d.ndim: {arr_2d.ndim}") # Output: 2
      ```

2.  **`shape`**:

    - **Description**: A tuple of integers indicating the size of the array in each dimension.
    - **Type**: Tuple of integers.
    - **Example**:

      ```python
      import numpy as np
      arr_1d = np.array([1, 2, 3])
      arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2 rows, 3 columns
      arr_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) # 2 "layers", 2 rows, 2 columns

      print(f"arr_1d.shape: {arr_1d.shape}") # Output: (3,)
      print(f"arr_2d.shape: {arr_2d.shape}") # Output: (2, 3)
      print(f"arr_3d.shape: {arr_3d.shape}") # Output: (2, 2, 2)
      ```

    - **Mutable**: You can change the shape of an array using `arr.shape = new_shape` or `arr.reshape()`, as long as the total number of elements remains the same.

3.  **`size`**:

    - **Description**: The total number of elements in the array. This is equal to the product of the elements of `shape`.
    - **Type**: Integer.
    - **Example**:
      ```python
      import numpy as np
      arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
      print(f"arr_2d.size: {arr_2d.size}") # Output: 6 (2 * 3)
      ```

---

## II. Data Type Information

These properties describe the type of data stored within the array.

1.  **`dtype`**:

    - **Description**: An object describing the data type of the elements in the array. This is fundamental for how NumPy stores and operates on data.
    - **Type**: `numpy.dtype` object.
    - **Example**:

      ```python
      import numpy as np
      arr_int = np.array([1, 2, 3])
      arr_float = np.array([1.0, 2.0])
      arr_bool = np.array([True, False])
      arr_str = np.array(['a', 'b'])

      print(f"arr_int.dtype: {arr_int.dtype}")       # Output: int64 (or int32 depending on system)
      print(f"arr_float.dtype: {arr_float.dtype}")   # Output: float64
      print(f"arr_bool.dtype: {arr_bool.dtype}")     # Output: bool
      print(f"arr_str.dtype: {arr_str.dtype}")       # Output: <U1 (Unicode string of length 1)
      ```

    - **Common dtypes**: `int8`, `int16`, `int32`, `int64`, `uint8`, `float16`, `float32`, `float64`, `complex64`, `complex128`, `bool`, `object`.

2.  **`itemsize`**:

    - **Description**: The size in bytes of each element of the array.
    - **Type**: Integer.
    - **Example**:

      ```python
      import numpy as np
      arr_int64 = np.array([1, 2, 3], dtype=np.int64)
      arr_float32 = np.array([1.0, 2.0], dtype=np.float32)

      print(f"arr_int64.itemsize: {arr_int64.itemsize} bytes")   # Output: 8 bytes (for int64)
      print(f"arr_float32.itemsize: {arr_float32.itemsize} bytes") # Output: 4 bytes (for float32)
      ```

3.  **`nbytes`**:

    - **Description**: The total bytes consumed by the array data. This is equal to `arr.size * arr.itemsize`.
    - **Type**: Integer.
    - **Example**:
      ```python
      import numpy as np
      arr = np.zeros((100, 100), dtype=np.float64) # 100x100 array of float64
      print(f"arr.nbytes: {arr.nbytes} bytes") # Output: 80000 bytes (100*100*8)
      ```

---

## III. Memory Layout and Internal Representation

These properties provide insights into how the array's data is stored in memory.

1.  **`strides`**:

    - **Description**: A tuple of integers indicating the number of bytes to skip in each dimension to go to the next element. It tells you how many bytes you need to move to get from one element to the next along a particular axis.
    - **Type**: Tuple of integers.
    - **Example**:

      ```python
      import numpy as np
      arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64) # Each int64 is 8 bytes
      print(f"arr.strides: {arr.strides}")
      # Output: (24, 8)
      # Explanation:
      # - To move from one row to the next (downwards, 1st dimension), you skip 3 elements * 8 bytes/element = 24 bytes.
      # - To move from one column to the next (rightwards, 2nd dimension), you skip 1 element * 8 bytes/element = 8 bytes.

      arr_c_order = np.array([[1, 2], [3, 4]], order='C') # Default C-order (row-major)
      arr_f_order = np.array([[1, 2], [3, 4]], order='F') # Fortran-order (column-major)

      print(f"arr_c_order.strides: {arr_c_order.strides}") # Output: (16, 8) for int64
      print(f"arr_f_order.strides: {arr_f_order.strides}") # Output: (8, 16) for int64
      ```

2.  **`flags`**:

    - **Description**: A dictionary-like object containing information about the memory layout of the array. Important flags include:
      - `C_CONTIGUOUS` / `C_ARRAY`: `True` if the data is C-contiguous (row-major).
      - `F_CONTIGUOUS` / `F_ARRAY`: `True` if the data is Fortran-contiguous (column-major).
      - `OWNDATA`: `True` if the array owns its own data (i.e., it's not a view of another array).
      - `WRITEABLE`: `True` if the data can be modified.
    - **Type**: `numpy.flagsobj` object.
    - **Example**:

      ```python
      import numpy as np
      arr = np.arange(6).reshape(2, 3)
      print("arr.flags:")
      print(arr.flags)
      # Output will show something like:
      #   C_CONTIGUOUS : True
      #   F_CONTIGUOUS : False
      #   OWNDATA : True
      #   WRITEABLE : True
      #   ALIGNED : True
      #   WRITEBACKIFCOPY : False

      view_arr = arr.view() # Create a view, not a copy
      print("\nview_arr.flags (OWNDATA is False):")
      print(view_arr.flags)
      # Output will show OWNDATA : False
      ```

---

## IV. Other Useful Properties

1.  **`real`**:

    - **Description**: The real part of the array elements. For non-complex dtypes, this is the array itself.
    - **Type**: `ndarray` (a view of the original or a copy).
    - **Example**:
      ```python
      import numpy as np
      arr_complex = np.array([1+2j, 3-4j])
      print(f"arr_complex.real: {arr_complex.real}") # Output: [1. 3.]
      arr_real = np.array([1, 2])
      print(f"arr_real.real: {arr_real.real}")       # Output: [1 2]
      ```

2.  **`imag`**:

    - **Description**: The imaginary part of the array elements. For non-complex dtypes, this will be an array of zeros.
    - **Type**: `ndarray` (a view of the original or a copy).
    - **Example**:
      ```python
      import numpy as np
      arr_complex = np.array([1+2j, 3-4j])
      print(f"arr_complex.imag: {arr_complex.imag}") # Output: [ 2. -4.]
      arr_real = np.array([1, 2])
      print(f"arr_real.imag: {arr_real.imag}")       # Output: [0. 0.]
      ```

3.  **`T`**:

    - **Description**: The transposed view of the array. For a 2D array, rows become columns and columns become rows. For higher dimensions, axes are permuted.
    - **Type**: `ndarray` (a view of the original).
    - **Example**:
      ```python
      import numpy as np
      arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
      print("Original 2D array:\n", arr_2d)
      print("Transposed 2D array (arr_2d.T):\n", arr_2d.T)
      # Output:
      # Original 2D array:
      #  [[1 2 3]
      #   [4 5 6]]
      # Transposed 2D array (arr_2d.T):
      #  [[1 4]
      #   [2 5]
      #   [3 6]]
      ```

4.  **`flat`**:

    - **Description**: An object that allows iteration over all elements of the array as if it were a 1D array, regardless of its original shape.
    - **Type**: `numpy.flatiter` object.
    - **Example**:
      ```python
      import numpy as np
      arr_2d = np.array([[1, 2], [3, 4]])
      print("Iterating using arr_2d.flat:")
      for x in arr_2d.flat:
          print(x, end=" ") # Output: 1 2 3 4
      ```

5.  **`base`**:

    - **Description**: The object whose memory is used by this array. If the array owns its own memory, its `base` attribute is `None`. This is useful for checking if an array is a view of another array.
    - **Type**: `ndarray` or `None`.
    - **Example**:

      ```python
      import numpy as np
      original_arr = np.array([1, 2, 3, 4, 5])
      view_arr = original_arr[1:4] # view_arr is a view of original_arr

      print(f"original_arr.base is None: {original_arr.base is None}") # Output: True
      print(f"view_arr.base is original_arr: {view_arr.base is original_arr}") # Output: True
      ```

Understanding these properties provides a deep insight into how NumPy arrays work and helps in writing more efficient and correct code for numerical operations.


NumPy's array indexing and slicing are powerful and highly flexible, allowing you to select and modify subsets of data efficiently. They are fundamental to almost any numerical operation with NumPy arrays. This functionality is inspired by Python's list slicing but extended to multiple dimensions.

Let's break down indexing and slicing in NumPy.

---

## I. Basic Indexing

Basic indexing is similar to Python list indexing for 1D arrays, but extends naturally to multiple dimensions.

### 1\. 1D Arrays (Vectors)

- **Single Element Access:** Use square brackets `[]` with an integer index.
  - Positive index: From the beginning (0-based).
  - Negative index: From the end (-1 is the last element).

<!-- end list -->

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original 1D array:", arr)

print("arr[0]:", arr[0])     # First element: 10
print("arr[2]:", arr[2])     # Third element: 30
print("arr[-1]:", arr[-1])   # Last element: 50
print("arr[-3]:", arr[-3])   # Third from last: 30
```

### 2\. Multi-Dimensional Arrays (Matrices, Tensors)

For arrays with more than one dimension, you provide an index for each dimension, separated by commas. The order of indices corresponds to the order of dimensions in `arr.shape`.

- `arr[row_index, col_index]` for 2D arrays.
- `arr[dim1_index, dim2_index, dim3_index]` for 3D arrays, and so on.

<!-- end list -->

```python
import numpy as np

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nOriginal 2D array:\n", arr_2d)

print("arr_2d[0, 0]:", arr_2d[0, 0]) # Element at row 0, col 0: 1
print("arr_2d[1, 2]:", arr_2d[1, 2]) # Element at row 1, col 2: 6
print("arr_2d[2, 1]:", arr_2d[2, 1]) # Element at row 2, col 1: 8

# Using negative indices
print("arr_2d[-1, -1]:", arr_2d[-1, -1]) # Last row, last col: 9
print("arr_2d[-2, 0]:", arr_2d[-2, 0])   # Second to last row, first col: 4
```

---

## II. Slicing

Slicing is used to extract subarrays. The syntax is `[start:stop:step]`, just like Python lists, but applied to each dimension.

- `start`: (Optional) The starting index (inclusive). Defaults to 0.
- `stop`: (Optional) The stopping index (exclusive). Defaults to the end of the dimension.
- `step`: (Optional) The step size. Defaults to 1.

**Key Concept: Views vs. Copies**
**Important**: Slicing in NumPy generally creates a **view** of the original array. This means that if you modify the slice, the original array will also be modified. If you need a completely independent copy, use the `.copy()` method.

### 1\. 1D Array Slicing

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original 1D array:", arr)

print("arr[1:4]:", arr[1:4])       # Elements from index 1 up to (but not including) 4: [20 30 40]
print("arr[:3]:", arr[:3])         # Elements from start up to 3: [10 20 30]
print("arr[4:]:", arr[4:])         # Elements from index 4 to end: [50 60 70]
print("arr[::2]:", arr[::2])       # Every second element: [10 30 50 70]
print("arr[::-1]:", arr[::-1])     # Reverse the array: [70 60 50 40 30 20 10]
print("arr[1:6:2]:", arr[1:6:2])   # From index 1 to 5, step 2: [20 40 60]

# Modifying a slice (modifies original array)
slice_arr = arr[1:4]
print("\nSlice arr[1:4]:", slice_arr)
slice_arr[0] = 99
print("Slice after modification:", slice_arr) # Output: [99 30 40]
print("Original array after slice modification:", arr) # Output: [10 99 30 40 50 60 70]
```

### 2\. Multi-Dimensional Array Slicing

You apply slicing to each dimension, separated by commas.

```python
import numpy as np

arr_2d = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])
print("\nOriginal 2D array:\n", arr_2d)

# Extract rows 0 and 1, all columns
print("\narr_2d[0:2, :]:\n", arr_2d[0:2, :])
# Output:
# [[1 2 3 4]
#  [5 6 7 8]]

# Extract all rows, columns 1 and 2
print("\narr_2d[:, 1:3]:\n", arr_2d[:, 1:3])
# Output:
# [[ 2  3]
#  [ 6  7]
#  [10 11]
#  [14 15]]

# Extract elements from row 1 to 2, and col 0 to 1
print("\narr_2d[1:3, 0:2]:\n", arr_2d[1:3, 0:2])
# Output:
# [[ 5  6]
#  [ 9 10]]

# Extract specific rows (e.g., row 0 and row 2), all columns
print("\narr_2d[[0, 2], :]:\n", arr_2d[[0, 2], :]) # Note: This is advanced indexing (see below)
# Output:
# [[ 1  2  3  4]
#  [ 9 10 11 12]]

# Using Ellipsis (...)
# The ellipsis simplifies selecting "all other dimensions".
# For a 2D array, arr[:, 1] is equivalent to arr[..., 1].
print("\narr_2d[..., 1]:\n", arr_2d[..., 1]) # All rows, column at index 1: [ 2  6 10 14]

arr_3d = np.arange(27).reshape(3, 3, 3)
print("\nOriginal 3D array:\n", arr_3d)

# Access a 2D slice (a 'layer')
print("\narr_3d[0, :, :]:\n", arr_3d[0, :, :])
# Or equivalent with ellipsis:
print("\narr_3d[0, ...]:\n", arr_3d[0, ...])

# Access a 1D slice (a 'row' across layers and columns)
print("\narr_3d[:, 1, 0]:\n", arr_3d[:, 1, 0])
# Output: [ 3 12 21] (elements (0,1,0), (1,1,0), (2,1,0))
```

---

## III. Advanced Indexing (Fancy Indexing)

Advanced indexing allows you to select non-contiguous or non-regular subsets of data using integer arrays or boolean arrays. This always returns a **copy** of the data, not a view.

### 1\. Integer Array Indexing

You can pass an array or list of integers for each dimension to select specific elements.

```python
import numpy as np

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nOriginal 2D array:\n", arr_2d)

# Select specific rows (rows 0 and 2)
print("\narr_2d[[0, 2]]:\n", arr_2d[[0, 2]])
# Output:
# [[1 2 3]
#  [7 8 9]]

# Select specific columns (columns 0 and 2)
print("\narr_2d[:, [0, 2]]:\n", arr_2d[:, [0, 2]])
# Output:
# [[1 3]
#  [4 6]
#  [7 9]]

# Select specific individual elements using a list of (row, col) tuples
# The result will be a 1D array.
rows = np.array([0, 1, 2])
cols = np.array([0, 2, 1]) # Select (0,0), (1,2), (2,1)
print("\narr_2d[rows, cols]:", arr_2d[rows, cols]) # Output: [1 6 8]

# Duplicate elements or reorder
print("\narr_2d[[0, 0, 1]]:\n", arr_2d[[0, 0, 1]]) # Select row 0 twice, then row 1
# Output:
# [[1 2 3]
#  [1 2 3]
#  [4 5 6]]
```

### 2\. Boolean Array (Mask) Indexing

You can use a boolean array of the same shape as the original array (or broadcastable to it) to select elements. Only elements corresponding to `True` values in the boolean array will be selected.

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("\nOriginal 1D array:", arr)

# Select elements greater than 30
mask = (arr > 30)
print("Boolean mask (arr > 30):", mask) # Output: [False False False  True  True]
print("arr[mask]:", arr[mask])         # Output: [40 50]
print("arr[arr > 30]:", arr[arr > 30]) # Common shorthand

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nOriginal 2D array:\n", arr_2d)

# Select elements that are even
even_mask = (arr_2d % 2 == 0)
print("\nBoolean mask for even numbers:\n", even_mask)
# Output:
# [[False  True False]
#  [ True False  True]
#  [False  True False]]

print("\narr_2d[even_mask]:", arr_2d[even_mask]) # Returns a 1D array of selected elements
# Output: [2 4 6 8]

# Select rows where the first element is > 4
row_mask = arr_2d[:, 0] > 4
print("\nBoolean mask for rows (first element > 4):", row_mask) # Output: [False  True  True]
print("arr_2d[row_mask]:\n", arr_2d[row_mask])
# Output:
# [[4 5 6]
#  [7 8 9]]
```

---

## IV. Combining Indexing and Slicing

You can mix basic indexing/slicing with advanced indexing. When you combine them, the basic indexing/slicing is performed first, and then the result is used for the advanced indexing.

```python
import numpy as np

arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print("Original 2D array:\n", arr_2d)

# Select rows 0 and 2 (advanced indexing), then slice columns 1 to 3 (basic slicing)
print("\narr_2d[[0, 2], 1:3]:\n", arr_2d[[0, 2], 1:3])
# This first selects rows [[1,2,3,4], [9,10,11,12]]
# Then applies [:, 1:3] to that intermediate result
# Output:
# [[ 2  3]
#  [10 11]]

# Select specific column (basic indexing), then apply boolean mask to that 1D array
print("\narr_2d[:, 0][arr_2d[:, 0] > 7]:", arr_2d[:, 0][arr_2d[:, 0] > 7])
# Output: [ 9 13]
```

---

## V. Assigning Values with Indexing and Slicing

You can assign values to specific elements or subarrays using the same indexing and slicing techniques.

```python
import numpy as np

arr_assign = np.zeros((3, 3), dtype=int)
print("Original array for assignment:\n", arr_assign)

# Assign a single value
arr_assign[0, 0] = 100
print("\nAfter arr_assign[0, 0] = 100:\n", arr_assign)

# Assign a row
arr_assign[1, :] = [1, 2, 3]
print("\nAfter arr_assign[1, :] = [1, 2, 3]:\n", arr_assign)

# Assign a column
arr_assign[:, 2] = 99
print("\nAfter arr_assign[:, 2] = 99:\n", arr_assign)

# Assign with a slice
arr_assign[0:2, 0:2] = 55
print("\nAfter arr_assign[0:2, 0:2] = 55:\n", arr_assign)

# Assign with boolean indexing
arr_assign[arr_assign > 50] = 77
print("\nAfter arr_assign[arr_assign > 50] = 77:\n", arr_assign)
```

---

Understanding NumPy's indexing and slicing is paramount for efficient data manipulation. Mastering the distinction between basic and advanced indexing (and the resulting view vs. copy behavior) is crucial for both performance and avoiding subtle bugs in your code.


NumPy's array operations are the core reason for its widespread use in scientific computing and data analysis. They enable highly efficient, vectorized computations on entire arrays, often vastly outperforming equivalent operations written with Python loops.

Let's explore the various types of operations you can perform on NumPy arrays, along with the underlying theoretical concepts like **vectorization** and **broadcasting**.

---

## I. Element-wise Operations (Vectorization)

This is the most common type of operation in NumPy. When you perform an arithmetic operation or a function call on an array, it's applied to each element individually. This is known as **vectorization**.

**Theory of Vectorization:**
Traditional Python loops iterate over elements one by one, which incurs significant overhead due to Python's dynamic typing and interpreter overhead. NumPy, on the other hand, implements these element-wise operations in optimized, pre-compiled C or Fortran code. When you write `arr1 + arr2`, NumPy doesn't actually loop in Python; it hands off the entire operation to a highly efficient C function that can process large blocks of memory very quickly. This is the primary source of NumPy's speed advantage.

### 1\. Arithmetic Operations

You can use standard arithmetic operators directly on NumPy arrays.

```python
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print("arr1:", arr1)
print("arr2:", arr2)

# Addition
print("arr1 + arr2:", arr1 + arr2)      # Output: [ 6  8 10 12]
print("np.add(arr1, arr2):", np.add(arr1, arr2)) # Equivalent function call

# Subtraction
print("arr1 - arr2:", arr1 - arr2)      # Output: [-4 -4 -4 -4]
print("np.subtract(arr1, arr2):", np.subtract(arr1, arr2))

# Multiplication (element-wise)
print("arr1 * arr2:", arr1 * arr2)      # Output: [ 5 12 21 32]
print("np.multiply(arr1, arr2):", np.multiply(arr1, arr2))

# Division (element-wise)
print("arr1 / arr2:", arr1 / arr2)      # Output: [0.2        0.33333333 0.42857143 0.5       ]
print("np.divide(arr1, arr2):", np.divide(arr1, arr2))

# Exponentiation
print("arr1 ** 2:", arr1 ** 2)          # Output: [ 1  4  9 16]
print("np.power(arr1, 2):", np.power(arr1, 2))

# Modulus
print("arr2 % arr1:", arr2 % arr1)      # Output: [0 0 1 0] (5%1=0, 6%2=0, 7%3=1, 8%4=0)
print("np.mod(arr2, arr1):", np.mod(arr2, arr1))
```

### 2\. Scalar Operations

You can perform arithmetic operations between an array and a single scalar value. NumPy applies the scalar to every element of the array.

```python
arr = np.array([1, 2, 3, 4])
print("\narr:", arr)

print("arr + 10:", arr + 10) # Output: [11 12 13 14]
print("arr * 3:", arr * 3)   # Output: [ 3  6  9 12]
```

### 3\. Comparison/Logical Operations

These operations also work element-wise and return boolean arrays.

```python
arr1 = np.array([1, 5, 3, 8])
arr2 = np.array([4, 5, 2, 8])

print("\narr1:", arr1)
print("arr2:", arr2)

print("arr1 > arr2:", arr1 > arr2)      # Output: [False False  True False]
print("arr1 == arr2:", arr1 == arr2)    # Output: [False  True False  True]
print("arr1 <= arr2:", arr1 <= arr2)    # Output: [ True  True False  True]

# Logical operations on boolean arrays
bool_arr1 = np.array([True, False, True])
bool_arr2 = np.array([False, True, True])

print("\nnp.logical_and(bool_arr1, bool_arr2):", np.logical_and(bool_arr1, bool_arr2)) # Output: [False False  True]
print("np.logical_or(bool_arr1, bool_arr2):", np.logical_or(bool_arr1, bool_arr2))   # Output: [ True  True  True]
print("np.logical_not(bool_arr1):", np.logical_not(bool_arr1))                       # Output: [False  True False]
```

### 4\. Universal Functions (ufuncs)

NumPy provides a vast collection of "universal functions" (ufuncs) that operate element-wise on `ndarray`s. These are highly optimized C functions that perform mathematical, trigonometric, exponential, and other operations.

```python
arr = np.array([-1.5, 0, 1.5, 2])

print("\narr:", arr)
print("np.abs(arr):", np.abs(arr))        # Absolute value: [1.5 0.  1.5 2. ]
print("np.sqrt(arr):", np.sqrt(np.array([1, 4, 9]))) # Square root: [1. 2. 3.] (note: sqrt on negative numbers results in NaN/complex)
print("np.sin(arr):", np.sin(arr))        # Sine
print("np.exp(arr):", np.exp(arr))        # Exponential e^x
print("np.log(np.array([1, 2, 3])):", np.log(np.array([1, 2, 3]))) # Natural logarithm
print("np.ceil(arr):", np.ceil(arr))      # Ceiling: [-1.  0.  2.  2.]
print("np.floor(arr):", np.floor(arr))    # Floor: [-2.  0.  1.  2.]
```

---

## II. Broadcasting

**Theory of Broadcasting:**
Broadcasting is a powerful mechanism in NumPy that allows arithmetic operations to be performed on arrays of different shapes. It's a set of rules that NumPy applies to "stretch" or "duplicate" the smaller array's dimensions to match the larger array's dimensions, without actually copying the data. This makes operations more memory-efficient and faster.

**Broadcasting Rules:**
For two arrays to be broadcastable, starting from the trailing dimension (rightmost) and working forward:

1.  **Equal Dimensions:** The dimensions must be equal.
2.  **One is One:** One of the dimensions is 1.
3.  **One is Missing:** One of the arrays does not have that dimension.

If these rules are met for all dimensions, the arrays are broadcastable. The resulting array's shape will be the maximum size along each dimension of the input arrays.

**Examples:**

```python
# Scalar and Array
arr = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
scalar = 10                          # shape ()

print("\nBroadcasting: scalar with 2D array")
print("arr + scalar:\n", arr + scalar)
# Output:
# [[11 12 13]
#  [14 15 16]]
# Theory: The scalar 10 is conceptually stretched to a (2,3) array of 10s.

# 1D array and 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr_1d = np.array([10, 20, 30])         # shape (3,)

print("\nBroadcasting: 1D array with 2D array")
print("arr_2d + arr_1d:\n", arr_2d + arr_1d)
# Output:
# [[11 22 33]
#  [14 25 36]]
# Theory: arr_1d (shape (3,)) is conceptually stretched across the rows of arr_2d.
# It effectively becomes:
# [[10 20 30]
#  [10 20 30]]

# More complex broadcasting example (adding a column vector to a matrix)
arr_matrix = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr_col_vec = np.array([[10], [20]])       # shape (2, 1)

print("\nBroadcasting: Column vector with matrix")
print("arr_matrix + arr_col_vec:\n", arr_matrix + arr_col_vec)
# Output:
# [[11 12 13]
#  [24 25 26]]
# Theory: arr_col_vec (shape (2,1)) is stretched across the columns of arr_matrix.
# It effectively becomes:
# [[10 10 10]
#  [20 20 20]]
```

---

## III. Aggregate Operations (Reductions)

These operations reduce the dimensions of an array, usually by computing a single value or a smaller array. The `axis` parameter is crucial here.

**Theory of `axis` parameter:**
The `axis` parameter specifies the dimension(s) along which the operation is performed.

- `axis=0`: Operation performed down the columns. The result will have one less dimension than the original array, corresponding to the aggregated rows.
- `axis=1`: Operation performed across the rows. The result will have one less dimension than the original array, corresponding to the aggregated columns.
- `axis=None` (default): Operation performed on the entire flattened array.

<!-- end list -->

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("\nOriginal array:\n", arr)

# Sum of all elements
print("Total sum (arr.sum()):", arr.sum())         # Output: 21
print("np.sum(arr):", np.sum(arr))                 # Equivalent function call

# Sum along rows (axis=0, collapses rows into a single row)
print("Sum along axis=0 (columns):", arr.sum(axis=0)) # Output: [5 7 9] (1+4, 2+5, 3+6)

# Sum along columns (axis=1, collapses columns into a single column)
print("Sum along axis=1 (rows):", arr.sum(axis=1))   # Output: [ 6 15] (1+2+3, 4+5+6)

# Other common aggregates:
print("Mean of all elements:", arr.mean())           # Output: 3.5
print("Min of all elements:", arr.min())             # Output: 1
print("Max along axis=0:", arr.max(axis=0))          # Output: [4 5 6]
print("Standard deviation:", arr.std())              # Output: 1.707825...
print("Cumulative sum (flattened):", arr.cumsum())   # Output: [ 1  3  6 10 15 21]
print("Cumulative sum along axis=1:\n", arr.cumsum(axis=1))
# Output:
# [[ 1  3  6]
#  [ 4  9 15]]
```

---

## IV. Matrix Operations (Linear Algebra)

NumPy's `numpy.linalg` module provides functions for advanced linear algebra operations. The `@` operator is specifically for matrix multiplication.

```python
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("\nMatrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

# Matrix multiplication (dot product)
print("\nMatrix A @ Matrix B:\n", matrix_a @ matrix_b)
# Output:
# [[1*5 + 2*7, 1*6 + 2*8]   [[19 22]
#  [3*5 + 4*7, 3*6 + 4*8]] = [43 50]]
print("np.dot(matrix_a, matrix_b):\n", np.dot(matrix_a, matrix_b)) # Equivalent function

# Transpose
print("\nMatrix A Transpose (A.T):\n", matrix_a.T)

# Determinant
print("\nDeterminant of A:", np.linalg.det(matrix_a))

# Inverse
try:
    print("\nInverse of A:\n", np.linalg.inv(matrix_a))
except np.linalg.LinAlgError as e:
    print(f"\nCould not compute inverse: {e}")

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
print("\nEigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)
```

---

## V. Array Manipulation Operations

These functions allow you to change the shape, combine, or split arrays.

### 1\. Reshaping

Changing the shape of an array without changing its data.

```python
arr = np.arange(1, 10) # 1D array from 1 to 9
print("\nOriginal 1D array:", arr)

reshaped_arr = arr.reshape(3, 3)
print("\nReshaped to 3x3:\n", reshaped_arr)

# Flattening an array
flat_arr = reshaped_arr.flatten() # Returns a copy
print("\nFlattened (copy):", flat_arr)

ravel_arr = reshaped_arr.ravel()   # Returns a view (if possible)
print("Raveled (view):", ravel_arr)
```

### 2\. Concatenation

Joining arrays along an existing axis.

```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertical concatenation (along axis=0, stacks rows)
v_stacked = np.vstack((arr1, arr2))
print("\nVertically stacked (vstack):\n", v_stacked)
# Equivalent to: np.concatenate((arr1, arr2), axis=0)

arr3 = np.array([[7], [8]])
# Horizontal concatenation (along axis=1, stacks columns)
h_stacked = np.hstack((arr1, arr3))
print("\nHorizontally stacked (hstack):\n", h_stacked)
# Equivalent to: np.concatenate((arr1, arr3), axis=1)
```

### 3\. Splitting

Dividing an array into multiple smaller arrays.

```python
arr = np.arange(9).reshape(3, 3)
print("\nOriginal array for splitting:\n", arr)

# Horizontal split (columns)
h_split = np.hsplit(arr, 3) # Split into 3 equal parts horizontally
print("\nHorizontal split (hsplit):\n", h_split)
# Output: [array([[0], [3], [6]]), array([[1], [4], [7]]), array([[2], [5], [8]])]

# Vertical split (rows)
v_split = np.vsplit(arr, [1, 2]) # Split after row 1 and row 2
print("\nVertical split (vsplit):\n", v_split)
# Output: [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
```

---

NumPy's array operations, underpinned by vectorization and broadcasting, are what make it an indispensable tool for data manipulation and numerical computation in Python. Mastering these operations is key to writing high-performance code for scientific and data-intensive applications.


## Universal Functions (Ufuncs) in NumPy: Theory and Practice

Universal Functions, or **ufuncs**, are the core of NumPy's vectorized operations. They are functions that operate on `ndarray`s element-by-element, supporting array broadcasting, type casting, and other standard features.

### I. What are Ufuncs? (The "What")

At their simplest, ufuncs are "vectorized" wrappers around C functions that perform element-wise operations on NumPy arrays. Instead of writing explicit Python loops to apply a function to each element of an array (which would be slow), you use a ufunc, and NumPy handles the looping internally at C speed.

**Examples of Ufuncs:**

- **Arithmetic:** `np.add`, `np.subtract`, `np.multiply`, `np.divide`, `np.power`, `np.mod`
- **Trigonometric:** `np.sin`, `np.cos`, `np.tan`, `np.arcsin`
- **Exponential/Logarithmic:** `np.exp`, `np.log`, `np.log10`, `np.log2`
- **Comparison:** `np.equal`, `np.not_equal`, `np.greater`, `np.less_equal`
- **Bitwise:** `np.bitwise_and`, `np.bitwise_or`, `np.invert`
- **Special Functions:** `np.sqrt`, `np.abs`, `np.floor`, `np.ceil`, `np.round`

Many of these ufuncs have Python operator equivalents (e.g., `+` for `np.add`, `*` for `np.multiply`), which are generally preferred for readability.

```python
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Using Python operators (internally calls ufuncs)
result_add = arr1 + arr2
result_mul = arr1 * 2

# Using explicit ufuncs
result_add_ufunc = np.add(arr1, arr2)
result_sqrt_ufunc = np.sqrt(arr1)
result_max_ufunc = np.maximum(arr1, arr2) # Element-wise maximum

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"arr1 + arr2 (operator): {result_add}")
print(f"np.add(arr1, arr2) (ufunc): {result_add_ufunc}")
print(f"np.sqrt(arr1) (ufunc): {result_sqrt_ufunc}")
print(f"np.maximum(arr1, arr2) (ufunc): {result_max_ufunc}")
```

### II. The Theory Behind Ufuncs (The "Why")

Ufuncs achieve their speed and efficiency through several key theoretical concepts:

1.  **Vectorization (Eliminating Python Loops):**

    - **Theory:** The fundamental principle. Instead of writing a Python `for` loop to apply an operation to each element, ufuncs perform the operation on an entire array (or multiple arrays) at once. The actual looping is done in pre-compiled C code, which is significantly faster because it avoids the overhead of Python's interpreter, dynamic type checking, and object creation for each iteration.
    - **Benefit:** Orders of magnitude speed improvement for large arrays, making numerical computations feasible.

2.  **Contiguous Memory Layout:**

    - **Theory:** NumPy arrays generally store their data in contiguous blocks of memory (C-contiguous by default). This allows ufuncs to process data efficiently by sequentially accessing memory, taking advantage of CPU cache locality and hardware optimizations (like SIMD instructions – Single Instruction, Multiple Data).
    - **Benefit:** Faster memory access and processing, as the CPU can pre-fetch data.

3.  **Broadcasting:**

    - **Theory:** Ufuncs inherently support broadcasting. When you perform an operation between arrays of different shapes, NumPy applies a set of rules to "stretch" the smaller array's dimensions to match the larger one for the purpose of the operation, without actually copying data. This means a scalar can be treated as an array of the same shape as the other operand, or a 1D array can be expanded to match the rows/columns of a 2D array.
    - **Benefit:** Enables operations between arrays of different shapes without explicit reshaping, making code more concise and memory-efficient.

4.  **Type Promotion and Type Casting:**

    - **Theory:** Ufuncs handle automatic type promotion. If you perform an operation between arrays of different data types (e.g., `int32` and `float64`), the ufunc will automatically promote the elements to the more general or higher-precision type (e.g., `float64`) to prevent data loss. You can also explicitly specify the `dtype` for the output.
    - **Benefit:** Ensures numerical stability and correctness, while allowing flexibility in input types.

5.  **Optimized C/Fortran Implementations:**

    - **Theory:** The core of ufuncs are highly optimized routines written in low-level languages like C or Fortran. These routines are often part of optimized libraries (like BLAS/LAPACK for linear algebra, which are called by NumPy for certain operations, though ufuncs are more general element-wise ops).
    - **Benefit:** Maximum performance leveraging decades of optimization in numerical computing.

### III. Properties and Methods of Ufuncs

Ufuncs themselves are objects with properties and methods that provide more control and information.

**Key Properties:**

- **`__name__`**: The name of the ufunc (e.g., `'add'`, `'sin'`).
- **`nin`**: Number of input arguments.
- **`nout`**: Number of output arguments.
- **`ntypes`**: Number of different `dtype` combinations the ufunc supports.
- **`types`**: A list of strings showing supported `dtype` signatures (e.g., `['ff->f', 'dd->d']`).

**Key Methods:**

1.  **`ufunc.reduce(array, axis=0, dtype=None, out=None, keepdims=False)`**

    - **Purpose:** Applies the ufunc cumulatively along a specified axis. Similar to `np.sum()`, `np.prod()`, `np.max()`, etc., but for _any_ binary ufunc.
    - **Example:**

      ```python
      arr = np.array([[1, 2, 3], [4, 5, 6]])
      print(f"\nOriginal array:\n{arr}")

      # Equivalent to np.sum(arr, axis=0)
      sum_cols = np.add.reduce(arr, axis=0)
      print(f"np.add.reduce(arr, axis=0): {sum_cols}") # Output: [5 7 9]

      # Equivalent to np.prod(arr)
      product_all = np.multiply.reduce(arr)
      print(f"np.multiply.reduce(arr): {product_all}") # Output: 720 (1*2*3*4*5*6)
      ```

2.  **`ufunc.accumulate(array, axis=0, dtype=None, out=None)`**

    - **Purpose:** Applies the ufunc cumulatively, returning an array of the same shape as the input with the accumulated results.
    - **Example:**

      ```python
      arr = np.array([1, 2, 3, 4])

      # Equivalent to np.cumsum(arr)
      cumsum_arr = np.add.accumulate(arr)
      print(f"\nnp.add.accumulate([1,2,3,4]): {cumsum_arr}") # Output: [ 1  3  6 10]
      ```

3.  **`ufunc.outer(a, b, **kwargs)`\*\*

    - **Purpose:** Computes the outer product of two arrays using the ufunc. If the ufunc is `multiply`, it's the standard outer product.
    - **Example:**

      ```python
      vec1 = np.array([1, 2])
      vec2 = np.array([3, 4, 5])

      # Equivalent to np.outer(vec1, vec2)
      outer_product = np.multiply.outer(vec1, vec2)
      print(f"\nnp.multiply.outer([1,2], [3,4,5]):\n{outer_product}")
      # Output:
      # [[ 3  4  5]
      #  [ 6  8 10]]
      ```

4.  **`ufunc.at(a, indices, b=None)`**

    - **Purpose:** Performs a "scatter" operation. It applies the ufunc to elements of `a` at specified `indices`, often combining them with values from `b`. Useful for in-place modification where indices might be repeated.
    - **Example:**

      ```python
      arr = np.zeros(5)
      indices = np.array([0, 1, 1, 3, 4, 3]) # Repeated indices
      values = np.array([1, 1, 1, 1, 1, 1])

      # Add 1 to positions 0, 1 (twice), 3 (twice), 4
      np.add.at(arr, indices, values)
      print(f"\nnp.add.at(zeros(5), [0,1,1,3,4,3], [1,1,1,1,1,1]): {arr}")
      # Output: [1. 2. 0. 2. 1.]
      ```

### IV. When to Use Ufuncs (and When Not To)

**Use Ufuncs When:**

- You need to perform element-wise operations on entire NumPy arrays.
- You want the highest possible performance for such operations.
- Your data fits into NumPy's homogeneous `ndarray` structure.
- You need to leverage broadcasting for operations on arrays of different shapes.

**Avoid Explicit Python Loops When:**

- You're iterating over large NumPy arrays and applying a simple element-wise operation. This is precisely what ufuncs are designed to optimize.

**Consider alternatives (e.g., `np.vectorize`, `apply_along_axis`, `frompyfunc`) when:**

- You have a **non-NumPy-aware Python function** that you absolutely need to apply element-wise, and you can't rewrite it with ufuncs. `np.vectorize` is a convenience wrapper for this, but it doesn't offer the performance benefits of true ufuncs as it still involves Python loops internally.
- You need more complex operations that go beyond simple element-wise transformations, possibly involving context from other parts of the array or more intricate logic (e.g., `np.apply_along_axis` for applying a function along a specific axis).

In essence, ufuncs are the reason NumPy is fast. They provide a high-performance bridge between Python's convenience and the low-level computational efficiency of C. By understanding and utilizing them, you can write powerful and efficient numerical code.
